#!/bin/bash

set -e

pathfind() {
    OLDIFS="$IFS"
    IFS=:
    for p in $PATH; do
        if [ -x "$p/$*" ]; then
            IFS="$OLDIFS"
            return 0
        fi
    done
    IFS="$OLDIFS"
    return 1
}

if `pathfind xdg-icon-resource` ; then
    for SIZE in 16 22 24 32 48 64 ; do
        xdg-icon-resource install --theme ubuntu-mono-dark --size ${SIZE} /usr/share/indicator-emojitwo/assets/icon-mono-dark-${SIZE}.png indicator-emojitwo || true
        xdg-icon-resource install --theme ubuntu-mono-light --size ${SIZE} /usr/share/indicator-emojitwo/assets/icon-mono-light-${SIZE}.png indicator-emojitwo || true
    done
    xdg-icon-resource forceupdate || true
fi